---
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directories: 
     - "/myconext-server/docker/"
     - "/servicedesk-gui/docker/"
     - "/myconext-gui/docker/"
     - "/account-gui/docker/"
    schedule:
      interval: "daily"
    groups:
      docker:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directories:
      - "/public-gui/"
      - "/servicedesk-gui/"
      - "/myconext-gui/"
      - "/account-gui/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    groups:
      frontends-prod:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      frontends-dev:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - "minor"
          - "patch"
  # Maintain dependencies for server
  - package-ecosystem: "maven"
    directories: 
     - "/**"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    groups:
      backend-prod:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      backend-dev:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - "minor"
          - "patch"

