package myconext.remotecreation;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import myconext.model.Verification;

import javax.validation.constraints.NotNull;
import java.io.Serializable;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class ExternalEduID implements Serializable {

    @NotNull
    private String email;
    @Schema(description = "Will be generated by the eduID API")
    private String eduIDValue;
    @NotNull
    private String chosenName;
    private String firstName;
    private String lastNamePrefix;
    private String lastName;
    @Schema(description = "Date of birth in the format 'yyyyMMdd' or 'yyyy-MM-dd'")
    private String dateOfBirth;
    private String identifier;
    @NotNull
    private Verification verification;
    @Schema(description = "Can be initial NULL")
    private String brinCode;

}
