package myconext.remotecreation;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import myconext.model.Verification;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.List;

@NoArgsConstructor
@Getter
@Setter
public class UpdateExternalEduID extends NewExternalEduID {

    @NotBlank
    @Schema(description = "Generated by the RemoteCreation POST API, must be send with PUT update requests")
    private String eduIDValue;

    public UpdateExternalEduID(String email, String eduIDValue, @NotBlank String chosenName, String firstName,
                               String lastNamePrefix, @NotBlank String lastName, String dateOfBirth, @NotBlank String identifier,
                               @NotNull Verification verification, List<String> brinCodes) {
        super(email, chosenName, firstName, lastNamePrefix, lastName, dateOfBirth, identifier, verification, brinCodes);
        this.eduIDValue = eduIDValue;
    }

    public UpdateExternalEduID(NewExternalEduID externalEduID, String newEduIDValue) {
        super(externalEduID.getEmail(),
                externalEduID.getChosenName(),
                externalEduID.getFirstName(),
                externalEduID.getLastNamePrefix(),
                externalEduID.getLastName(),
                externalEduID.getDateOfBirth(),
                externalEduID.getIdentifier(),
                externalEduID.getVerification(),
                externalEduID.getBrinCodes());
        this.eduIDValue = newEduIDValue;
    }

}
