const en = {
    code: "EN",
    name: "English",
    languages: {
        language: "Language",
        en: "English",
        nl: "Dutch",
    },
    landing: {
        header: {
            title: "ServiceDesk",
            subTitle: "",
            login: "Log in",
            sup: "EduID ServiceDesk is by invitation only.",
        },
        works: "How does it work?",
        info: [
            //Arrays of titles and info blocks and if a function is an admin function
            "SURF TODO.",
        ],
        footer: "<p>SURFconext ServiceDesk offers user validation for SURFconext-connected applications.</p>" +
            "<p>Do you want to know more? <a href='https://support.surfconext.nl/servicedesk-en'>Read more</a>.</p>",
    },
    header: {
        title: "SURFconext ServiceDesk",
        links: {
            logout: "Logout"
        }
    },
    serviceDesk: {
        member: "ServiceDesk member"
    },
    tabs: {
        home: "Home",
        verify: "Identity control"
    },
    verification: {
        header: "Enter the verification code",
        proceed: "Continue",
        error: "No user found for verification code {{code}}",
        info: "This code is generated by the user in eduID."
    },
    control: {
        header: "Identity control for code: ",
        restart: "Start again",
        proceed: "Continue",
        error: "An unexpected error has occurred. Please contact <a href='mailto:servicedesk@surf.nl>?subject=Reference {{reference}}'>SURF ServiceDesk</a>",
        info: "Control the ID of this user",
        validDocuments: "Valid documents: passports, EEA ID cards, Dutch driving licenses and Dutch residence permits",
        inValidDocuments: "Copies, public transport tickets and student cards are not valid documents",
        isValid: "Is this all correct?",
        validations: {
            photo: "The person <span>looks like the photo</span> in the document",
            valid: "The document is <span>still valid</span>",
            lastName: "The last name in the document: <span>{{lastName}}</span>",
            firstName: "The first names in the document: <span>{{firstName}}</span>",
            dayOfBirth: "The date of birth in the document: <span>{{dayOfBirth}}</span> ",
        },
        invalidDate: "The day of birth can not be recognized, please select the correct date",
        validDate: "The day of birth is corrected",
        idDocument: "Fill in the <span>last 6 characters</span> of the ID document",
    },
    confirmation: {
        header: "The identity of the person has been confirmed",
        info: "From now on, the person will see a check mark in front of the personal data in eduID",
        restart: "Back to home"
    },
    footer: {
        terms: "Terms of Use",
        termsLink: "https://support.surfconext.nl/terms-en",
        privacy: "Privacy policy",
        privacyLink: "https://support.surfconext.nl/privacy-en",
        surfLink: "https://surf.nl",
    },

}

export default en;
