name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v5
      with:
        node-version: '24.3.0'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 4.4
    - name: Install MongoDB Tools
      run: sudo apt-get update && sudo apt-get install -y mongodb-org-shell mongodb-org-tools
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
    - name: Load users.json to MongoDB
      run: |
          mongoimport \
            --host localhost \
            --port 27017 \
            --db myconext \
            --collection users \
            --file myconext-server/src/test/resources/users.json \
            --jsonArray
    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
#    - name: Build with Maven
#      run: mvn clean install --file pom.xml
    - name: Run myconext-server
      run : cd myconext-server && mvn spring-boot:run -Dspring-boot.run.profiles=dev &
    - name: Run account-gui
      run: cd account-gui && nvm use && yarn install && yarn dev &
    - name: Run myconext--gui
      run: cd myconext-gui && nvm use && yarn install && yarn dev &
    - name: Run servicedesk-gui
      run: cd servcedesk-gui && nvm use && yarn install && yarn dev &
    - name: Run public-gui
      run: cd public-gui && nvm use && yarn install && yarn dev &
    - name: Install dependencies for plarwright
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
